version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: dockerfile

    container_name: ula-landings
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "composer install --ignore-platform-reqs && php ./src/scripts/index.php"


  nginx:
     image: nginx:1.17-alpine
     container_name: backend-nginx
     restart: unless-stopped
     ports:
       - "8000:80"
     volumes:
       - ./docker-compose/nginx:/etc/nginx/conf.d

